In [9]:
import pandas as pd
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression

In [2]:
total_ans_feature_df = pd.read_csv('StackOverflowAndroidAnsweredFeaturesTotal.csv')

In [3]:
total_ans_feature_df.columns

Index(['Unnamed: 0', 'Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId',
       'CreationDate', 'DeletionDate', 'Score', 'ViewCount', 'Body',
       'OwnerUserId', 'OwnerDisplayName', 'LastEditorUserId',
       'LastEditorDisplayName', 'LastEditDate', 'LastActivityDate', 'Title',
       'Tags', 'AnswerCount', 'CommentCount', 'FavoriteCount', 'ClosedDate',
       'CommunityOwnedDate', 'ParentId.1', 'first_response', 'number_of_days',
       'lines_of_code', 'number_of_code_tags', 'average_sent_length',
       'urls_count', 'sent_length', 'word_count', 'SBAR', 'SBARQ', 'SQ'],
      dtype='object')

In [4]:
from datetime import datetime
from dateutil import parser
def date_diff(first_response, CreationDate):
    dt = parser.parse(first_response)
    dt1 = parser.parse(CreationDate)
    diff = dt - dt1
    return diff.total_seconds()/3600 # divide by 3600 to convert to hours

In [5]:
def get_class(hr):
    if 0 <= hr <= 1:
        return 1
    elif 1< hr <= 2:
        return 2
    elif 2< hr<= 4:
        return 4
    elif 4< hr <=10:
        return 10;
    elif hr > 10:
        return 11

In [6]:
hr_diff_list = []
hr_y = []
count ={}
for index, row in total_ans_feature_df.iterrows():
    hr_diff = date_diff(row['first_response'], row['CreationDate'])
    hr_diff_list.append(hr_diff)
    cls = get_class(hr_diff)
    if cls in count:
        count[cls] = count[cls]+ 1
    else:
        count[cls] = 1
    hr_y.append(cls)
    
total_ans_feature_df['hr_diff'] = hr_diff_list
total_ans_feature_df['y_hr'] = hr_y
total_ans_feature_df = total_ans_feature_df.fillna(0)

In [7]:
count
1:0.45
2:0.9
4:0.92
10:0.93
11:0.8
    
9270

SyntaxError: illegal target for annotation (<ipython-input-7-0a633c7f7e46>, line 2)

In [8]:
total_ans_feature_df[8500:8600][['CreationDate','first_response','hr_diff', 'y_hr']]
total_ans_feature_df[0:1]

Unnamed: 0        Id  PostTypeId  AcceptedAnswerId  ParentId  \
0           0  54002492           1        54666886.0       0.0   

          CreationDate  DeletionDate  Score  ViewCount  \
0  2019-01-02 07:05:39           0.0      0         50   

                                                Body  ...  \
0  <p>how can i perform login without OTP verific...  ...   

   number_of_code_tags average_sent_length  urls_count sent_length word_count  \
0                    0                11.0           0           2         22   

  SBAR SBARQ   SQ      hr_diff  y_hr  
0  0.0   0.0  0.5  1010.561944    11  

[1 rows x 37 columns]

In [ ]:
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression

x = total_ans_feature_df[['lines_of_code', 'number_of_code_tags', 'average_sent_length',
       'urls_count', 'sent_length', 'word_count', 'SBAR', 'SBARQ', 'SQ']]

y = total_ans_feature_df['y_hr']

X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=7)

X_train[0:1]

In [44]:
clf = LogisticRegression(random_state=7, solver='lbfgs', multi_class='multinomial',class_weight={1:0.05,2:0.25,4:0.3,10:0.3,11:0.1}, max_iter=4000).fit(X_train, y_train)

In [ ]:
1:0.45
2:0.9
4:0.92
10:0.93
11:0.8
{1: 5102, 2: 920, 4: 712, 10: 664, 11: 1872}


In [30]:
pre = clf.predict(X_test)
pre
# print (accuracy_score(y_test, pre))
# print(classification_report(y_test, pre))

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [31]:
clf = GaussianNB().fit(X_train, y_train)

In [45]:
pre = clf.predict(X_test)
print (accuracy_score(y_test, pre))
print(classification_report(y_test, pre))

0.472851492268968
              precision    recall  f1-score   support

           1       0.58      0.80      0.67      1537
           2       0.10      0.05      0.07       292
           4       0.11      0.06      0.08       219
          10       0.09      0.14      0.11       190
          11       0.36      0.06      0.10       543

   micro avg       0.47      0.47      0.47      2781
   macro avg       0.25      0.22      0.20      2781
weighted avg       0.42      0.47      0.41      2781



In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='linear', C=10,class_weight={1:0.05,2:0.25,4:0.3,10:0.3,11:0.1}).fit(X_train, y_train)


In [ ]:
pre = clf.predict(X_test)
print (accuracy_score(y_test, pre))
print(classification_report(y_test, pre))

In [11]:
x = total_ans_feature_df[['lines_of_code', 'number_of_code_tags', 'average_sent_length',
       'urls_count', 'sent_length', 'word_count', 'SBAR', 'SBARQ', 'SQ']]

y = total_ans_feature_df['hr_diff']

X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.3, random_state=7)

In [12]:
reg = LinearRegression().fit(X_train, y_train)

In [14]:
y_pred = reg.predict(X_test)

In [15]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_test, y_pred))

In [16]:
rms

71.90143475522919

In [17]:
from sklearn import svm
clf = svm.SVR(kernel='linear', C=1).fit(X_train, y_train)


In [22]:
from sklearn.metrics import mean_squared_error
from math import sqrt
y_pred = clf.predict(X_train)
rms = sqrt(mean_squared_error(y_train, y_pred))
rms

74.14737396692193

In [40]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model

poly = PolynomialFeatures(degree=5)
X_ = poly.fit_transform(X_train)
predict_ = poly.fit_transform(X_train)

clf = linear_model.LinearRegression()
clf.fit(X_, y_train)
y_pred = clf.predict(predict_)

In [41]:
from sklearn.metrics import mean_squared_error
from math import sqrt
# y_pred = clf.predict(X_train)
rms = sqrt(mean_squared_error(y_train, y_pred))
rms

63.3980617542366

In [44]:
from sklearn import preprocessing
import numpy as np


# Normalize total_bedrooms column
normalized_X = preprocessing.normalize(x)

In [47]:
print (normalized_X)

[[0.         0.         0.44565103 ... 0.         0.         0.02025687]
 [0.01585217 0.04755652 0.         ... 0.01056811 0.         0.        ]
 [0.23079075 0.06861347 0.08420743 ... 0.0053465  0.         0.        ]
 ...
 [0.46784712 0.03772961 0.08753269 ... 0.01131888 0.         0.00377296]
 [0.02216415 0.01108207 0.15293262 ... 0.01108207 0.         0.00277052]
 [0.         0.         0.31612552 ... 0.01234865 0.         0.        ]]


In [48]:
print(y)

0       1010.561944
1        999.480556
2        875.291111
3        896.880000
4        855.983889
5        855.314167
6        803.234167
7        772.374722
8        800.926944
9        785.583611
10       785.031389
11       784.035556
12       743.839167
13       712.019444
14       725.888889
15       727.263611
16       722.474722
17       697.970833
18       688.804444
19       714.852500
20       690.010278
21       673.671111
22       664.290833
23       670.561111
24       666.151389
25       641.008333
26       652.090833
27       659.636944
28       621.829167
29       631.132500
           ...     
9240       0.336944
9241       0.487222
9242       1.600278
9243       0.679444
9244       0.202500
9245       3.454167
9246       0.148333
9247       0.062222
9248       0.235000
9249       0.039167
9250       0.894722
9251       0.379167
9252       0.324722
9253       1.929444
9254       0.227500
9255       0.500556
9256       0.630833
9257       0.578333
9258       0.126111


In [51]:
x = total_ans_feature_df[['lines_of_code', 'number_of_code_tags', 'average_sent_length',
       'urls_count', 'sent_length', 'word_count', 'SBAR', 'SBARQ', 'SQ']]

y = total_ans_feature_df['hr_diff']

normalized_X = preprocessing.normalize(x)

X_train, X_test, y_train, y_test = model_selection.train_test_split(normalized_X, y, test_size=0.3, random_state=7)

In [52]:
reg = LinearRegression().fit(X_train, y_train)

In [53]:
y_pred = reg.predict(X_test)

In [59]:
rms = sqrt(mean_squared_error(y_test, y_pred))
rms

72.02058899131256